/**
 * @file InventoryDialogDefs.hpp
 * @author sbobovyc
 */

#define HEADGEAR_SLIDER	101
#define HEADGEAR_BUTTON	102
#define UNIFORM_SLIDER	103
#define UNIFORM_BUTTON	104
#define VEST_SLIDER	105
#define VEST_BUTTON	106
#define BACKPACK_SLIDER 107
#define BACKPACK_BUTTON 108
#define WEAPON_SLIDER	109
#define WEAPON_BUTTON	110
#define SECONDARY_WEAPON_BUTTON	111
#define SECONDARY_WEAPON_SLIDER	112

#define UNIFORM_LOAD 197
#define VEST_LOAD 198
#define BACKPACK_LOAD 199
#define TOTAL_LOAD 200
#define MULTIPURPOSE_LISTBOX 201
#define ADD_ITEM_BUTTON 202
#define REMOVE_ITEM_BUTTON 203
#define MULTIPURPOSE_NLISTBOX 300

#define MAIN_TITLE "Stan's Visual Inventory System"
