STEAM_USER=$1
PASS=$2
ARMA_ID=107410
ARMA_SERVER_ID=233780
RHSUSAF_ID=843577117
RHSAFRF_ID=843425103
RHSGREF_ID=843593391
CBA3_ID=450814997
CUP_WEAPONS_ID=497660133
CUP_UNITS_ID=497661914
CUP_VEHICLES_ID=541888371
CUP_TERRAINS_CORE_ID=583496184
CUP_TERRAINS_MAPS_ID=583544987
COMMUNITY_FACTIONS_PROJECT_ID=1369691841
IFA3_LITE_ID=878977835

INSTALL_DIR=/home/$USER/Arma3
WORKSHOP_DIR=$INSTALL_DIR/steamapps/workshop/content

download_mod() {
	MODID=$1
	steamcmd +login $STEAM_USER $PASS +force_install_dir $INSTALL_DIR +workshop_download_item $ARMA_ID $MODID validate +quit
}

steamcmd +login $STEAM_USER $PASS +force_install_dir $INSTALL_DIR +app_update $ARMA_SERVER_ID +quit
download_mod $RHSUSAF_ID
download_mod $RHSAFRF_ID
download_mod $RHSGREF_ID
download_mod $CBA3_ID
download_mod $CUP_WEAPONS_ID
download_mod $CUP_VEHICLES_ID
download_mod $CUP_UNITS_ID
download_mod $CUP_TERRAINS_CORE_ID
download_mod $CUP_TERRAINS_MAPS_ID
download_mod $COMMUNITY_FACTIONS_PROJECT_ID
download_mod $IFA3_LITE_ID

ln -s -T $WORKSHOP_DIR/$ARMA_ID/$RHSUSAF_ID $INSTALL_DIR/@rhsusaf
ln -s -T $WORKSHOP_DIR/$ARMA_ID/$RHSAFRF_ID $INSTALL_DIR/@rhsafrf
ln -s -T $WORKSHOP_DIR/$ARMA_ID/$RHSGREF_ID $INSTALL_DIR/@rhsgref
ln -s -T $WORKSHOP_DIR/$ARMA_ID/$CBA3_ID $INSTALL_DIR/@cba_a3
ln -s -T $WORKSHOP_DIR/$ARMA_ID/$CUP_WEAPONS_ID $INSTALL_DIR/@cup_weapons
ln -s -T $WORKSHOP_DIR/$ARMA_ID/$CUP_VEHICLES_ID $INSTALL_DIR/@cup_vehicles
ln -s -T $WORKSHOP_DIR/$ARMA_ID/$CUP_UNITS_ID $INSTALL_DIR/@cup_units
ln -s -T $WORKSHOP_DIR/$ARMA_ID/$CUP_TERRAINS_CORE_ID $INSTALL_DIR/@cup_terrains
ln -s -T $WORKSHOP_DIR/$ARMA_ID/$CUP_TERRAINS_MAPS_ID $INSTALL_DIR/@cup_maps
ln -s -T $WORKSHOP_DIR/$ARMA_ID/$COMMUNITY_FACTIONS_PROJECT_ID $INSTALL_DIR/@cfp
ln -s -T $WORKSHOP_DIR/$ARMA_ID/$IFA3_LITE_ID $INSTALL_DIR/@ifa3_lite

find $WORKSHOP_DIR -name *.bikey -exec cp {} $INSTALL_DIR/keys \;

mkdir -p ~/".local/share/Arma 3" && mkdir -p ~/".local/share/Arma 3 - Other Profiles"
